// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WPF_MVVM_DB_Example.Models
{
    public partial class TempItem
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
    }
}