// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WPF_MVVM_DB_Example.Models
{
    public partial class TempItemContext : DbContext
    {

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source =; database=; User ID=; Password=; Integrated Security=True; Encrypt=False;");

        }
        public TempItemContext()
        {
        }

        public TempItemContext(DbContextOptions<TempItemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TempItem> TempItems { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TempItem>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("TempItem");

                entity.Property(e => e.Id).HasMaxLength(50);

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.SerialNumber).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}